# Generated by Django 4.1.2 on 2022-10-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student_name')),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default=0, max_length=120)),
                ('district', models.CharField(choices=[('Kottayam', 'Kottayam'), ('Ernakulam', 'Ernakulam'), ('Kollam', 'Kollam'), ('Kozhikodu', 'Kozhikodu'), ('Alapuzha', 'Alapuzha')], default='Kottayam', max_length=30)),
                ('Branch', models.CharField(choices=[('Kottayam', 'Kottayam'), ('Aluva', 'Aluva'), ('Kollam', 'Kollam'), ('Kozhikodu', 'Kozhikodu'), ('Alapuzha', 'Alapuzha')], default='Kottayam', max_length=50)),
                ('Accounttype', models.CharField(choices=[('Saving', 'Saving'), ('Current', 'Current'), ('Business', 'Business')], default='Saving', max_length=50)),
                ('materials', models.CharField(choices=[('creditcard', 'creditcard'), ('debitcard', 'debitcard'), ('chequebook', 'chequebook')], default='Saving', max_length=50)),
            ],
        ),
    ]
